# Generated by Django 3.2.9 on 2022-01-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20220115_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='favorites',
        ),
    ]
