# Generated by Django 3.2.9 on 2022-01-15 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0003_remove_advertisement_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavorAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert', models.ManyToManyField(related_name='favorites', to='advertisements.Advertisement')),
                ('user', models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
